apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-depl
  labels:
    app: mongo
spec:
  replicas: 1
  serviceName: 'mongo'
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: db-bs-claim
      containers:
        - name: mongo
          image: mongo
          volumeMounts:
            - mountPath: '/data/db'
              name: mongo-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-bs-claim
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-srv
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
